#!/bin/bash

while getopts ":c:p:d:" opt; do
  case $opt in
    c) current_date="$OPTARG"
    ;;
    p) prediction_date="$OPTARG"
    ;;
    d) path_to_lsh_data="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

cd lsh_data_processing
Rscript covid19_lsh_data_processing.R -c "$current_date" -p "$prediction_date" -d "$path_to_lsh_data"
cd ../src
make
./covid "$current_date" ..
cd ../R
Rscript -e 'args <- commandArgs(TRUE);Sys.setenv(RSTUDIO_PANDOC="/Applications/RStudio.app/Contents/MacOS/pandoc"); rmarkdown::render("report.Rmd", "html_document",output_file=paste0("../daily_report/",args[1],"-Flæði COVID-19 sjúklinga LSH.html"))' "$current_date"