---
title: "LSH - BCS Gagnaborð"
author: ''
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    css: styles.css
---

```{r global, include=FALSE, warning=FALSE}
library(flexdashboard)
library(shiny)
library(plotly)
library(ggplot2)
library(stringr)
library(dplyr)
library(readr)
library(tidyr)
library(RCurl)
source('dashboard_functions.R')

#Load csv data
bcs_data <- readRDS('input/bcs_data.rds')
bcs_data$data_length_of_stay <- bcs_data$data_length_of_stay %>% recode_states()

# Set constants
start_date <- min(bcs_data$data_length_of_stay$date) # as.Date('2020-04-02')
end_date <- Sys.Date()
gagnagerdir <- unique(bcs_data$data_length_of_stay$censored)
aldurshopar <- unique(bcs_data$data_length_of_stay$age_group_simple) #list('0-50', '51+')
states <- unique(bcs_data$data_length_of_stay$state)
```


Skýrslur {id=skyrslur data-icon="fa-th-large"}
=======================================================================

Stillingar {.sidebar}
-------------------------------------------------------------

```{r}
helpText('Veljið dagsetningu til að birta skýrslu fyrir')
sliderInput('dagsetning_sk', 'Dagsetning:', 
            min = start_date, max = max(bcs_data$data_all_simulation$date),
            value = max(bcs_data$data_all_simulation$date), step = 1, timeFormat = "%d %b")
actionButton('saekja_gogn', label = 'Sækja ný gögn')
observeEvent(input$saekja_gogn, {
  msg <- get_and_save_new_data(bcs_data)
  showNotification(msg, duration = 4, id = 'msg_saekja_gogn', type = 'message')
  bcs_data <- readRDS('input/bcs_data.rds')
  bcs_data$data_length_of_stay <- bcs_data$data_length_of_stay %>% recode_states()
})
```


skyrsla-header {data-height=50px}
-----------------------------------------------------------

#### Spá um fjölda smitaðra einstaklinga í hverri stöðu á hverjum degi


```{r simulation_data}
# Make the simulation data reactive on date slider
data_simulation_quantiles <- reactive({
  bcs_data$data_all_simulation %>% 
    filter(date == input$dagsetning_sk) %>%
    mutate(date_spa = date + day) %>%
    gather(key = 'state', value = 'count', 2:6) %>% 
    recode_states() %>% 
    group_by(date_spa, state) %>% 
    summarize(median = round(median(count)), 
              quantile975 = round(quantile(count, probs=0.975))) %>%
    ungroup()
})

#' Plot plots from the forecast report. Requires the data_simulation_quantiles reactive to exist
plot_simulation <- function(state) {
    if(nrow(data_simulation_quantiles()[data_simulation_quantiles()$state==state, ]) < 1) {
        ggplot() +
            geom_text(aes(x=10, y = 10, label = 'Spá vantar')) +
            lims(x=c(0,30), y=c(0,100)) +
            theme_minimal()
        stop()
    }
    p_data <- data_simulation_quantiles()[data_simulation_quantiles()$state==state, ] %>% 
        gather('key', 'value', -date_spa, -state) %>%
        mutate(key = key %>% recode(median = "Líkleg spá",
                                    quantile975 = "Svartsýn spá"))
    ggplot(data = p_data, aes(x = date_spa, y = value)) +
        geom_line(aes(linetype = key, alpha = key), col = "blue4") +
        # scale_x_date(date_breaks = "2 days", date_labels = "%m-%d", expand = c(0,0.5)) +
        labs(x = '', y = 'Fjöldi', linetype = '', alpha = '') +
        scale_alpha_manual(values = c(1, 0.7)) +
        theme_minimal()
}

# Göngudeild
window_size <- 7

outpatient_clinic_sim_visits <- reactive({
  prop_visit_for_date <- data_prop_visits %>%
    filter(date == input$dagsetning_sk - window_size) %>%
    select(prop_visits_last_week) %>%
    as.numeric()
  bcs_data$data_all_simulation %>%
    mutate(count_visits = home * prop_visit_for_date) %>%
    group_by(date) %>%
    summarise(median = round(median(count_visits)),
              quantile975 = round(quantile(count_visits,probs=0.975))) %>%
    ungroup()
})
```

skyrsla-efri-röð
--------------------------------------

### Heimaeinangrun

```{r}
renderPlotly({
    p <- plot_simulation('Heimaeinangrun')
    p <- p + ylim(0,1000)
    ggplotly(p, tooltip = list('linetype', 'date', 'value'))
})
```


### Göngudeild

```{r}
renderPlotly({
    p <- ggplot() + theme_minimal()
    ggplotly(p)
})
# renderPlotly({
#     p_data <- outpatient_clinic_sim_visits() %>%
#     gather('key', 'value', -date) %>%
#     mutate(key = key %>% recode(median = "Líkleg spá",
#                                 quantile975 = "Svartsýn spá"))
#   ggplot(data = p_data,
#          aes(x = date, y = value)) +
#     geom_line(aes(lty = key), col = "blue4", size = 0.7) +
#     labs(x = '', y = 'Fjöldi') +
#     theme_minimal() +
#     theme(legend.position = "top",
#           legend.title = element_blank())
# })
```

skyrsla-neðri-röð
------------------------------

### Legudeild
```{r}
renderPlotly({
    p <- plot_simulation('Legudeild')
    p <- p + ylim(0, 50)
    ggplotly(p, tooltip = list('linetype', 'date', 'value'))
})
```


### Gjörgæsla
```{r}
renderPlotly({
    p <- plot_simulation('Gjörgæsla')
    p <- p + ylim(0, 20)
    ggplotly(p, tooltip = c("value", "date", "key"))
})
```

<!-- Skýrsla footer {data-height=30} -->
<!-- ------------------------- -->
<!-- - Þetta spálíkan spáir fyrir um fjölda einstaklinga fjórar vikur fram í tímann.  -->
<!-- - Spálíkanið nýtir tvenns konar gögn, annars vegar spá um fjölda nýrra smita sem fæst af síðunni covid.hi.is og hins vegar söguleg gögn um Covid sjúklinga frá Landspítalanum.  -->
<!-- - Komur á göngudeild eru áætlaðar út frá spáðum fjölda í heimaeinangrun og hlutfalli þeirra sem voru í heimaeinangrun í síðustu viku og komu á göngudeild. -->


Sviðsmyndir {id=svidsmyndir data-icon="fa-project-diagram"}
===============================================

Stillingar {.sidebar}
---------------------------------------------------

```{r}
# sliderInput('dagsetning', 'Dagsetning:', min = start_date, max = end_date,
#             value = end_date, step = 1, timeFormat = "%d %b")
helpText('Sláið inn nýjar auka forsendur og veljið "Keyra hermun". 
         Nokkurn tíma gæti tekið fyrir keyrsluna að klárast.')
dateInput('sv_date', 'Dagsetning', value = '2020-03-01', min = '2020-03-01', max = Sys.Date() + 30)

div(numericInput('sv_fjoldi', 'Fjöldi', min = 0, max = 100, step = 1, value = 0, width = 20),  selectInput('sv_age', 'Aldursbil', choices = c('0-50', '51-75', '>75'), selected = '0-50', width = 20), id='groupInputs')
div(numericInput('sv_fjoldi', 'Fjöldi', min = 0, max = 100, step = 1, value = 0, width = 20),  selectInput('sv_age', 'Aldursbil', choices = c('0-50', '51-75', '>75'), selected = '51-75', width = 20), id='groupInputs')
div(numericInput('sv_fjoldi', 'Fjöldi', min = 0, max = 100, step = 1, value = 0, width = 20),  selectInput('sv_age', 'Aldursbil', choices = c('0-50', '51-75', '>75'), selected = '+75', width = 20), id='groupInputs')

actionButton("sv_keyra", "Keyra hermun")

```


sviðsmyndir-legudeild
-------------------------------

### Legudeild

```{r}
renderPlotly({
  p <- plot_simulation('Legudeild') + ylim(0, 100)
  ggplotly(p, tooltip = list('linetype', 'date', 'value'))
  observeEvent(input$sv_keyra, {
    p <- p + geom_line(aes(y = value + 5, lty = key, size = 'Ný sviðsmynd'), col = "red", size = 0.7)
    ggplotly(p, tooltip = list('linetype', 'date', 'value'))
  })    
  ggplotly(p, tooltip = list('linetype', 'date', 'value'))
})

```

sviðsmyndir-gjörgæsla
------------------------------

### Gjörgæsla

```{r}
renderPlotly({
    p <- plot_simulation('Gjörgæsla') + ylim(0, 50)
    if (input$sv_fjoldi > 0) {
    p <- p + 
      geom_line(aes(y = value + 2, lty = key, size = 'Ný sviðsmynd'), col = "red", size = 0.7)
    }
    ggplotly(p, tooltip = list('linetype', 'date', 'value'))
})
```


Forsendur {data-icon="fa-chart-bar"}
=======================================================================

Stillingar {.sidebar}
---------------------------------------------------

```{r}
sliderInput('dagsetning', 'Dagsetning:', min = start_date, max = max(bcs_data$data_length_of_stay$date),
            value = end_date, step = 1, timeFormat = "%d %b")
checkboxInput('festa_asa', 'Festa ása', value = FALSE)
checkboxGroupInput('aldur', label = 'Aldurshópar:', 
                   choices = aldurshopar, selected = aldurshopar)
checkboxGroupInput('state', label = 'Staða:', 
                   choices = states, selected = states)
checkboxGroupInput('gagnagerd', label = 'Censored:',
                   choices = gagnagerdir, selected = gagnagerdir)
selectInput('fill_by', 'Lita eftir:', c(names(bcs_data$data_length_of_stay)[1:3]), selected = 'censored')
selectInput('facet', 'Facet eftir:', c('-', names(bcs_data$data_length_of_stay)[1:3]))

```

dreifinga-tabs {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Length of Stay 

```{r}
dataset <- reactive({
  bcs_data$data_length_of_stay %>%  
    filter(date == input$dagsetning,
           state %in% input$state,
           age_group_simple %in% input$aldur, 
           censored %in% input$gagnagerd)
})

# renderText(print(as.Date(input$dagsetning, origin = '1970-01-01', format="%d %b")))
renderPlot({
  p <- ggplot(dataset(), aes(x=state_duration, y=count, fill = censored)) + 
    geom_col(position = 'dodge') +
    scale_fill_manual(values = palette1) +
    # scale_fill_viridis_d(begin = 0.1, end = 0.6) +
    theme_minimal()
  
  p <- p + aes_string(fill = input$fill_by)
  
  if (input$facet != '-')
    p <- p + facet_wrap(paste0('~', input$facet), scales = 'free')
  if(input$festa_asa)
    p <- p + lims(x = c(0, 35), y = c(0, max(bcs_data$data_length_of_stay$count)))
  print(p)
})
```


### Transition Matrix Test [WIP]

```{r}
links <- list(
  source = c(0,1,0,1,2),
  target = c(1,2,3,3,3),
  value =  c(4,2,2,2,2))
  
nodes <-  list(
  label = c("home", "inpatient_ward", "intensive_care_unit", "recovered"),
  color = c("blue", "blue", "blue", "blue"),
  pad = 15,
  thickness = 20,
  line = list(
    color = "black",
    width = 0.5
  )
)

fig <- plot_ly(
  type = "sankey",
  orientation = "h",
  node = nodes,
  link = links
)

fig <- fig %>% layout(
  title = "Basic Sankey Diagram",
  font = list(
    size = 10
  )
)

fig
```


<!-- Gagnagæði {data-icon="fa-tasks"} -->
<!-- ======================================================================= -->

<!-- Stillingar {.sidebar} -->
<!-- --------------------------------------------------- -->

