int get_index(char* string, char c);
int get_person_index(int person_id);
int clear_symbol(char *buffer, char s);
int get_state(char *szstate);
int get_splitting_variable(char *szsplitvar);
int readForecast(char *fname, char *szStartDate, int num_sim_days);
int readFirstCDF(char *fname, char *date_last_observed);
int readLosCDF(char *fname, char *date_last_observed);
int readTransitionCDF(char *fname, char *date_last_observed);
int readInfectedAtStart(char *fname, char *sim_start_date);
int readHistoricalData(char *fname, char *szDate, int max_sim_time);
int readHistoricalArrival(char *fname, char *szDate, int day);
int readScenarioFirstCDF(char *fname);
int readScenarioData(char *fname, char *szDate, int max_sim_time);
