int get_index(char* string, char c);
int clear_symbol(char *buffer, char s);
int get_state(char *szstate);
int get_splitting_variable(char *szsplitvar);
int readHIposteriors(char *fname, char *szDate, int day, double *dbl);
int readFirstCDF(char *fname);
int readLosP(char *fname);
int readTransitionCDF(char *fname);
int readHistoricalData(char *fname, char *szDate, int max_sim_time);
int readHistoricalArrival(char *fname, char *szDate, int day);
int get_person_index(int person_id);
int readScenarioData(char *fname, char *szDate, int max_sim_time);